#!/usr/bin/env bash
# Start proxy independently (context-proxy, port 8096).
#
# Forward to PROXY_UPSTREAM_URL, independently of the memory group's MEMORY_LLM_* settings.
# Proxy calls memory-core:8420 for authentication, Skills, and memory injection, and memory-hub:8125
# for the sessionInit control plane. Standalone startup disables or degrades unavailable features.
#
# Usage:
#   ./start-proxy.sh
#
# Required proxy settings in .env:
#   PROXY_UPSTREAM_URL / PROXY_UPSTREAM_API_KEY / PROXY_UPSTREAM_MODEL

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_lib.sh
source "$SCRIPT_DIR/_lib.sh"

load_env
require_vars \
  PROXY_IMAGE PROXY_PORT \
  PROXY_UPSTREAM_URL PROXY_UPSTREAM_API_KEY PROXY_UPSTREAM_MODEL

# Use the same internal gateway credential as memory-core (default local, for local testing only).
MEMORY_CORE_GATEWAY_API_KEY="${MEMORY_CORE_GATEWAY_API_KEY:-local}"

CONTAINER=tdai-proxy
NETWORK=tdai-memory-stack

if ! $DOCKER network inspect "$NETWORK" >/dev/null 2>&1; then
  info "Creating Docker network $NETWORK"
  $DOCKER network create "$NETWORK" >/dev/null
fi

# Check dependencies without blocking startup.
if ! $DOCKER ps --format '{{.Names}}' 2>/dev/null | grep -qx "tdai-memory-core"; then
  warn "memory-core is not running; Proxy authentication, memory, and Skill injection will degrade."
fi
if ! $DOCKER ps --format '{{.Names}}' 2>/dev/null | grep -qx "tdai-memory-hub"; then
  warn "memory-hub is not running; the Proxy sessionInit control plane is unavailable."
fi

pull_image "$PROXY_IMAGE"
rm_container_if_exists "$CONTAINER"

# Proxy reads the upstream URL / API key from YAML, not the PROXY_UPSTREAM_URL environment variable.
# Generate a minimal config.yaml from .env and mount it at /data/config.yaml.
# The container CMD already specifies --config /data/config.yaml.
CONFIG_DIR="${PROXY_CONFIG_DIR:-$SCRIPT_DIR/.proxy-config}"
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/config.yaml"

# Three feature switches: minimal defaults, with dependencies enabled automatically.
# PROXY_ENABLE_AUTH: verify x-tdai-user-key through Core auth/verify to resolve user_id.
# PROXY_ENABLE_SESSION_INIT: first-turn team/agent/task selection; depends on auth and tdai.
# PROXY_ENABLE_TDAI: inject L2/L3 and recall L1; depends on memory-core.
#
# PROXY_FULL_STACK=1 enables all three features.
if [[ "${PROXY_FULL_STACK:-0}" == "1" ]]; then
  PROXY_ENABLE_AUTH=1
  PROXY_ENABLE_TDAI=1
  PROXY_ENABLE_SESSION_INIT=1
fi
PROXY_ENABLE_AUTH="${PROXY_ENABLE_AUTH:-0}"
PROXY_ENABLE_TDAI="${PROXY_ENABLE_TDAI:-0}"
PROXY_ENABLE_SESSION_INIT="${PROXY_ENABLE_SESSION_INIT:-0}"

# sessionInit requires auth to resolve user_id; enable auth automatically when sessionInit is enabled.
if [[ "$PROXY_ENABLE_SESSION_INIT" == "1" && "$PROXY_ENABLE_AUTH" != "1" ]]; then
  warn "PROXY_ENABLE_SESSION_INIT=1 requires auth; enabling PROXY_ENABLE_AUTH automatically."
  PROXY_ENABLE_AUTH=1
fi

bool() { [[ "$1" == "1" ]] && echo "true" || echo "false"; }

info "Generating Proxy config → $CONFIG_FILE  (auth=$(bool $PROXY_ENABLE_AUTH) session-init=$(bool $PROXY_ENABLE_SESSION_INIT) tdai=$(bool $PROXY_ENABLE_TDAI))"
cat > "$CONFIG_FILE" <<YAML
# Generated by start-proxy.sh. Overwritten on every startup; do not edit manually.
server:
  host: 0.0.0.0
  port: 8096
  forwardTimeoutMs: 600000

upstream:
  url: "${PROXY_UPSTREAM_URL}"
  apiKey: "${PROXY_UPSTREAM_API_KEY}"

log:
  file: ""
  level: info
  backend: console

# TDAI Core integration for injection, Skills, and authentication.
tdai:
  enabled: $(bool $PROXY_ENABLE_TDAI)
  endpoint: "http://memory-core:8420"
  apiKey: "${MEMORY_CORE_GATEWAY_API_KEY}"
  serviceId: default
  memory:
    enabled: true
    inject: true
    writeL0: true
    recallL1: true
    injectL2L3: true

skill:
  endpoint: "http://memory-core:8420"
  serviceToken: "${MEMORY_CORE_GATEWAY_API_KEY}"

# Knowledge injector registration requirements (shouldRegisterKnowledgeInjector):
# All three are required: knowledge in injectors, knowledge.enabled, and knowledge.serviceToken.
# Without this section the injector is silently skipped and <knowledge_tools> never appears.
knowledge:
  enabled: $(bool $PROXY_ENABLE_TDAI)
  endpoint: "http://memory-core:8420"
  serviceToken: "${MEMORY_CORE_GATEWAY_API_KEY}"
  serviceId: default

auth:
  enabled: $(bool $PROXY_ENABLE_AUTH)
  url: "http://memory-core:8420"
  timeoutMs: 5000

sessionInit:
  enabled: $(bool $PROXY_ENABLE_SESSION_INIT)
  maxRetries: 3
  injectAgentContext: true
  injectTaskContext: true
  headerAutoSelect:
    enabled: true
    teamHeader: "x-team-id"
    agentHeader: "x-agent-id"
    taskHeader: "x-task-id"
    onMismatch: "form"

costGuard:
  enabled: false

# Enable the skill, knowledge, and tdai-memory injectors.
# Knowledge requires memory-hub; otherwise its hook degrades to an empty block.
injection:
  enabled: true
  injectors:
    - skill
    - knowledge
    - tdai-memory

redis:
  enabled: false
YAML

info "Starting Proxy (image=$PROXY_IMAGE, port=$PROXY_PORT)"
$DOCKER run -d --name "$CONTAINER" \
  --network "$NETWORK" \
  --network-alias proxy \
  --add-host=host.docker.internal:host-gateway \
  -p "${PROXY_PORT}:8096" \
  -v "$CONFIG_FILE:/data/config.yaml:ro" \
  "$PROXY_IMAGE" >/dev/null

wait_healthy "$CONTAINER" 90
ok "Proxy started → http://localhost:${PROXY_PORT}/"
ok "  Usage: point your coding agent's API base to http://localhost:${PROXY_PORT}"
